---
title: "journal"
author: "Hayden Simm"
date: "2026-03-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We are deciding to work in the tidyverse, so we loading in the data using "read_csv" 

possible things to investigate:
- look at how different tissues are activated with the different acclimation conditions
- look at acclimation and body condition 
- MANOVA 

Boxplot: plotted the assay temp by enzyme activity and body condition. Grouped the values by 
acclimation temperature. 

COX activity plot shows that the 10 degrees acclimated enzyme is has higher activity than the 24 degrees acclimated fish. Means the fish has 
higher capacity for oxygen consumption.. so because it was acclimated at this temperature it can perform better than the warm acclimated fish??
When in warmer temperatures COX activities are similar for the different temperature acclimated scenarios  

CS activity plot has 10 degree acclimated lower than than the 24 degrees acclimated for both test temperatures 

Few outliers in the body condition plot. 10 degrees acclimated have better body condition than the 24 degree acclimated. 


The diagnostic plots for the Lm for body condition (response) with predictors temperature and salinity acclimation, assay temperature and fish ID  all are valid. This model has a linear pattern, has equal variance, there are not any influential points, and has normality. On the Q-Q plot there are some high and low points but they are minimal and majority of points are along the line.

from the alleffects plot can see that body condition is slightly higher for the 10 degrees acclimated. Salinity doesn't really change it..

COX activity- the gills,liver,spleen- marker of total mitochondrial capacity 
CS activity- total mitochondrial presence
LDH activity- liver, gill, muscle, brain- anerobic capacity 


Need to compare the activity between all three and see if indication of tissue..